LOAD DATA LOCAL INFILE 'bidders.csv' INTO TABLE Bidders FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'sellers.csv' INTO TABLE Sellers FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'items.csv' INTO TABLE Items FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'categories.csv' INTO TABLE Categories FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'bids.csv' INTO TABLE Bids FIELDS TERMINATED BY '|*|';