LOAD DATA LOCAL INFILE 'users.csv' INTO TABLE Users FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'items.csv' INTO TABLE Items FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'categories.csv' INTO TABLE Categories FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'bids.csv' INTO TABLE Bids FIELDS TERMINATED BY '|*|';